### ISSUE TITLE
"pgcrypto" not available on Tembo

### ISSUE THREAD

**Issue by nilsonsales** [tembo-io/tembo#1029]
Hello,

I have a simple application that uses `pgcrypto`. I tried to enable it on Tembo with the command:
```sql
CREATE EXTENSION pgcrypto;
```

But I got the following error:

> SQL Error [0A000]: ERROR: extension "pgcrypto" is not available
  Detail: Could not open extension control file "/var/lib/postgresql/data/tembo/extension/pgcrypto.control": No such file or directory.
  Hint: The extension must first be installed on the system where PostgreSQL is running.

It's just a hobby application, but it used to work fine on ElephantSQL.
Is it possible to make it available?

Thanks in advance :)

**Comment by ChuckHend** [comment]
Hi @nilsonsales, `pgcrypto` is available, but you will first need to install it into your Tembo instance. In the UI at cloud.tembo.io, go to `Extensions -> Explore -> Search for and select pgcrypto -> Click 'Install Extension' -> Enable Extension`.

Installing Extension installs the extension from pgt.dev into your Postgres cluster, then Enable Extension runs `CREATE EXTENSION` for you.

**Comment by nilsonsales** [comment]
Thank you for the detailed instructions!
