### ISSUE TITLE
any self host option?

### ISSUE THREAD

**Issue by agaitan026** [tembo-io/tembo#480]
tembo is only cloud? or have self host?

**Comment by ChuckHend** [comment]
This repo contains the tembo-operator which is what we use in our cloud. That can be installed in your kubernetes cluster if you want to self-host.
https://tembo.io/docs/tembo-stacks/tembo-operator-install

**Comment by ianstanton** [comment]
Hey @agaitan026! I'm going to close this issue as we've been chatting in our Tembo Community Slack :)
