### ISSUE TITLE
Incorrect documentation about PSQL ATER VIEW on temb.io

### ISSUE THREAD

**Issue by egidijusz** [tembo-io/tembo#712]
Hello,

here https://tembo.io/docs/getting-started/postgres_guides/how-to-create-views-in-postgres it says, that to ALTER a view one needs to do this:
```
ALTER VIEW adult_users AS
SELECT id, age
FROM users
WHERE age >= 20;
```

This is not a valid postgresql statement. More info on [stackoverflow](https://stackoverflow.com/questions/65682511/postgresql-alter-view-as) and [official documentation](https://www.postgresql.org/docs/current/sql-alterview.html).

Correct statement:
```
CREATE OR REPLACE VIEW adult_users AS
SELECT id, age
FROM users
WHERE age >= 20;
```

**Comment by ianstanton** [comment]
Thanks @egidijusz! We've opened a PR to update this example statement:
- https://github.com/tembo-io/website/pull/474

For future reference, community members are welcome to edit these pages and we welcome all contributions :)

You'll find this link at the bottom of our docs and guides:
![image](https://github.com/tembo-io/tembo/assets/8935584/bb582d41-c5d6-41ec-9a14-bab0c552a03a)

**Comment by ianstanton** [comment]
Resolved by https://github.com/tembo-io/website/pull/474
