### ISSUE TITLE
The instance status remains RESTARTING and nothing can be done.

### ISSUE THREAD

**Issue by pea-sys** [tembo-io/tembo#915]
* 1.Add the invalid configuration

![タイトルなし](https://github.com/user-attachments/assets/172a6157-c5c5-4734-bb65-c2454d5cf4b4)

* 2.Restart the instance

* 3.After waiting a while it still said it was restarting, so I tried restarting it again, but the restart button was disabled and I couldn't do anything.

![タイトルなし1](https://github.com/user-attachments/assets/3ea8fbb7-44f5-4a16-8e8c-999134544bde)

**Comment by joshuajerin** [comment]
Hello pea! Could you please open up a support ticket by sending us an email to support@tembo.io to assist you better? Thank you!
